# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/fastermodels',
                'doc_host': 'https://FasterAI-Labs.github.io',
                'git_url': 'https://github.com/FasterAI-Labs/fastermodels',
                'lib_path': 'fastermodels'},
  'syms': {}}
