# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/fastermodels',
                'doc_host': 'https://FasterAI-Labs.github.io',
                'git_url': 'https://github.com/FasterAI-Labs/fastermodels',
                'lib_path': 'fastermodels'},
  'syms': { 'fastermodels.model': { 'fastermodels.model.FasterModel': ('model.html#fastermodel', 'fastermodels/model.py'),
                                    'fastermodels.model.FasterModel.__init__': ('model.html#fastermodel.__init__', 'fastermodels/model.py'),
                                    'fastermodels.model.FasterModel._from_pretrained': ( 'model.html#fastermodel._from_pretrained',
                                                                                         'fastermodels/model.py'),
                                    'fastermodels.model.FasterModel.forward': ('model.html#fastermodel.forward', 'fastermodels/model.py'),
                                    'fastermodels.model.FasterModel.wrap': ('model.html#fastermodel.wrap', 'fastermodels/model.py'),
                                    'fastermodels.model._plain': ('model.html#_plain', 'fastermodels/model.py'),
                                    'fastermodels.model._swap': ('model.html#_swap', 'fastermodels/model.py'),
                                    'fastermodels.model.resolve': ('model.html#resolve', 'fastermodels/model.py'),
                                    'fastermodels.model.spec_from': ('model.html#spec_from', 'fastermodels/model.py'),
                                    'fastermodels.model.state_hash': ('model.html#state_hash', 'fastermodels/model.py')}}}
