# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_card.ipynb.

# %% ../nbs/02_card.ipynb #imports
from __future__ import annotations

import re

from .eval import wilson

# %% auto #0
__all__ = ['FORBIDDEN', 'render_card', 'check_card']

# %% ../nbs/02_card.ipynb #card
FORBIDDEN = ('lossless', 'un moteur int8', 'an int8 engine', 'state-of-the-art', 'sota', 'verified',
             'nan', 'ok=false', 'inconclusive', 'todo', 'tbd', 'xxx', 'placeholder')

_DEVICES = ('cpu', 'gpu', 'orin', '5090', 'jetson')
_RUNTIMES = ('tensorrt', 'onnxruntime', 'ort', 'openvino', 'pytorch', 'torchscript', 'eager')
_SPEEDUP = re.compile(r'\b\d+(?:\.\d+)?\s?[x×](?!\w)', re.I)


def _accuracy(k, n):
    "k/n in percent, with its Wilson 95 % interval"
    lo, hi = wilson(k, n)
    return f"{k}/{n} = {100 * k / n:.2f} % (Wilson 95 % [{100 * lo:.2f}, {100 * hi:.2f}])"


def _is_count(v):
    "A measured count, never a bool passing itself off as one"
    return isinstance(v, int) and not isinstance(v, bool)


def _count(v):
    "A count the producer measured, or n/a"
    return f"{v:,}" if _is_count(v) else 'n/a'


def _gap(artifact, reference):
    "Change from the reference in percent; never a ratio, a smaller model is not a faster one"
    if not (_is_count(artifact) and _is_count(reference) and reference): return 'n/a'
    return f"{100 * (artifact - reference) / reference:+.1f} %"


def render_card(
    meta: dict,  # name, base_model, license, datasets, tags, scope_line, input_shape, recipe, rows, latency, provenance, and reference: name, k, n, bytes, params, macs, peak_activation_bytes
) -> str:
    "Render the model card: front matter, scope, recipe, the four criteria against the reference, latency and provenance"
    ref, latency = meta['reference'], meta.get('latency')
    missing = [f for f in ('name', 'k', 'n') if f not in ref]
    if missing: raise KeyError(f"meta['reference'] has no {missing} — the card names what it compares to, and on how many images")
    out = ['---', 'library_name: fastermodels', f"license: {meta['license']}", f"base_model: {meta['base_model']}", 'datasets:']
    out += [f"  - {d}" for d in meta.get('datasets', [])]
    out += ['tags:'] + [f"  - {t}" for t in meta.get('tags', ['fasterai'])]
    out += ['---', '', f"# {meta['name']}", '', meta['scope_line'], '', '## Recipe', '']
    out += [f"- `{k}`: {v}" for k, v in (meta.get('recipe') or {}).items()]
    out += ['', '## Criteria', '',
            f"Top-1 on the evaluation set named above, size on disk, peak live activations and "
            f"multiply-accumulates — the last two for one image of {meta.get('input_shape', 'the evaluation resolution')} "
            f"at batch 1 — each against **{ref['name']}**.", '']
    for r in meta.get('rows', []):
        out += [f"### {r['artifact']} (`{r['file']}`)", '',
                '| criterion | reference | this artifact | gap |', '|---|---|---|---|',
                f"| top-1 | {_accuracy(ref['k'], ref['n'])} | {_accuracy(r['k'], r['n'])} "
                f"| {r['delta']:+.2f} pt, 95 % CI [{r['lo']:+.2f}, {r['hi']:+.2f}], McNemar p {r['p_mcnemar']:.4f} |",
                f"| size | {_count(ref.get('bytes'))} B, {_count(ref.get('params'))} params "
                f"| {_count(r.get('bytes'))} B, {_count(r.get('params'))} params "
                f"| {_gap(r.get('bytes'), ref.get('bytes'))} bytes, {_gap(r.get('params'), ref.get('params'))} params |",
                f"| memory | {_count(ref.get('peak_activation_bytes'))} B | {_count(r.get('peak_activation_bytes'))} B "
                f"| {_gap(r.get('peak_activation_bytes'), ref.get('peak_activation_bytes'))} |",
                f"| MACs | {_count(ref.get('macs'))} | {_count(r.get('macs'))} | {_gap(r.get('macs'), ref.get('macs'))} |", '']
    out += ['## Latency', '']
    if not latency: out += ['non mesurée']
    else:
        out += ['| device | runtime | precision | batch | median (ms) | runs |', '|---|---|---|---|---|---|']
        out += [f"| {r['device']} | {r['runtime']} | {r['precision']} | {r['batch']} | {r['median_ms']} | {r['n_runs']} |"
                for r in latency]
    out += ['', '## Provenance', ''] + [f"- {k}: `{v}`" for k, v in (meta.get('provenance') or {}).items()]
    return '\n'.join(out) + '\n'


def check_card(
    text: str,  # the card to read back
) -> list[str]:
    "Every forbidden phrase and every speedup claim without both a device and a runtime on its line; empty when the card is clean"
    found = [p for p in FORBIDDEN if re.search(rf"\b{re.escape(p)}\b", text, re.I)]
    for line in text.splitlines():
        claim, low = _SPEEDUP.search(line), line.lower()
        if claim and not (any(w in low for w in _DEVICES) and any(w in low for w in _RUNTIMES)):
            found.append(f"{claim.group().strip()} without both a device and a runtime on its line")
    return found
