# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_card.ipynb.

# %% ../nbs/02_card.ipynb #imports
from __future__ import annotations

import re

# %% auto #0
__all__ = ['FORBIDDEN', 'render_card', 'check_card']

# %% ../nbs/02_card.ipynb #card
FORBIDDEN = ('lossless', 'un moteur int8', 'an int8 engine', 'state-of-the-art', 'sota', 'verified',
             'nan', 'ok=false', 'inconclusive', 'todo', 'tbd', 'xxx', 'placeholder')

_DEVICES = ('cpu', 'gpu', 'orin', '5090', 'jetson')
_RUNTIMES = ('tensorrt', 'onnxruntime', 'ort', 'openvino', 'pytorch', 'torchscript', 'eager')
_SPEEDUP = re.compile(r'\b\d+(?:\.\d+)?\s?[x×](?!\w)', re.I)
_HUB_ID = re.compile(r'^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$')   # what the Hub accepts in `base_model:`


def _is_count(v):
    "A measured count, never a bool passing itself off as one"
    return isinstance(v, int) and not isinstance(v, bool)


def _top1(k, n):
    "Top-1 in percent; the number of images is in the scope line, once"
    return f"{100 * k / n:.1f} %"


def _mb(v):
    "A size in megabytes, or n/a"
    return f"{v / 1e6:.1f} MB" if _is_count(v) else 'n/a'


def _millions(v):
    "A count in millions, or in billions past a thousand million"
    if not _is_count(v): return 'n/a'
    return f"{v / 1e9:.2f} G" if v >= 1e9 else f"{v / 1e6:.1f} M"


def _gap(artifact, reference):
    "Change from the reference in percent; never a ratio, a smaller model is not a faster one"
    if not (_is_count(artifact) and _is_count(reference) and reference): return 'n/a'
    return f"{100 * (artifact - reference) / reference:+.1f} %"


def render_card(
    meta: dict,  # name, base_model, license (a string, or id and validated_by), datasets, tags, scope_line, input_shape, rows, latency, provenance, optional recipe, ladder and gate, and reference: name, k, n, bytes, params, macs, peak_activation_bytes
) -> str:
    "Render the model card: front matter, scope, the absolute top-1, the three criteria against the reference, latency and provenance"
    ref, latency = meta['reference'], meta.get('latency')
    missing = [f for f in ('name', 'k', 'n') if f not in ref]
    if missing: raise KeyError(f"meta['reference'] has no {missing} — the card names what it compares to, and on how many images")
    lic = meta['license']
    lic_id = lic['id'] if isinstance(lic, dict) else lic
    validated = lic.get('validated_by') if isinstance(lic, dict) else lic   # a plain string is one a person chose
    base = meta['base_model']
    hub_id = _HUB_ID.match(base)
    out = (['---', 'library_name: fastermodels'] + ([f"license: {lic_id}"] if validated else [])
           + ([f"base_model: {base}"] if hub_id else []) + ['datasets:'])
    out += [f"  - {d}" for d in meta.get('datasets', [])]
    out += ['tags:'] + [f"  - {t}" for t in meta.get('tags', ['fasterai'])]
    out += ['---', '', f"# {meta['name']}", '', meta['scope_line'], '']
    if meta.get('recipe'):
        out += ['## Recipe', ''] + [f"- `{k}`: {v}" for k, v in meta['recipe'].items()] + ['']
    out += ['## Criteria', '',
            f"Top-1 on the evaluation set named above; size on disk, peak live activations and "
            f"multiply-accumulates — the last two for one image of {meta.get('input_shape', 'the evaluation resolution')} "
            f"at batch 1 — each against **{ref['name']}**.", '']
    for r in meta.get('rows', []):
        w = r.get('wilson')
        interval = f" [{100 * w[0]:.1f}, {100 * w[1]:.1f}]" if w else ''
        out += [f"### {r['artifact']} (`{r['file']}`)", '',
                f"Top-1: {_top1(r['k'], r['n'])}{interval} on {r['n']} images", '',
                '| criterion | reference | this artifact | gap |', '|---|---|---|---|',
                f"| size | {_mb(ref.get('bytes'))}, {_millions(ref.get('params'))} params "
                f"| {_mb(r.get('bytes'))}, {_millions(r.get('params'))} params "
                f"| {_gap(r.get('bytes'), ref.get('bytes'))} |",
                f"| memory | {_mb(ref.get('peak_activation_bytes'))} | {_mb(r.get('peak_activation_bytes'))} "
                f"| {_gap(r.get('peak_activation_bytes'), ref.get('peak_activation_bytes'))} |",
                f"| MACs | {_millions(ref.get('macs'))} | {_millions(r.get('macs'))} | {_gap(r.get('macs'), ref.get('macs'))} |"]
        for note in r.get('notes') or []: out += ['', note]
        out += ['']
    if meta.get('rows'):
        out += ['Top-1 brackets give the 95 % interval over the evaluation images; size, memory and MACs gaps '
                'are against the reference.', '']
    if meta.get('ladder'):
        out += ['## Variants', '', 'Other points on the same ladder, from the same source model:', '',
                '| variant | repo | top-1, worst published form | size | memory | MACs |',
                '|---|---|---|---|---|---|']
        out += [f"| {v['name']} | `{v['repo']}` | {_top1(v['k'], v['n']) if {'k', 'n'} <= v.keys() else 'n/a'} "
                f"| {_mb(v.get('bytes'))} | {_mb(v.get('peak_activation_bytes'))} | {_millions(v.get('macs'))} |"
                for v in meta['ladder']]
        out += ['']
    out += ['## Latency', '']
    if not latency: out += ['not measured']
    else:
        out += ['| device | runtime | precision | batch | median (ms) | runs |', '|---|---|---|---|---|---|']
        out += [f"| {r['device']} | {r['runtime']} | {r['precision']} | {r['batch']} | {r['median_ms']} | {r['n_runs']} |"
                for r in latency]
    out += (['', '## Provenance', ''] + ([] if hub_id else [f"- Source model: {base}"])
            + [f"- {k}: `{v}`" for k, v in (meta.get('provenance') or {}).items()])
    if not validated: out += [f"- License: {lic_id} (not yet validated by a person)"]
    if meta.get('gate'):
        failed = [g['name'] for g in meta['gate'] if not g['passed']]
        out += ['', f"Publication checks: {len(meta['gate']) - len(failed)}/{len(meta['gate'])} structural "
                    "checks passed."
                    + (f" Not passed: {', '.join(failed)}." if failed else '')]
    return '\n'.join(out) + '\n'


def check_card(
    text: str,  # the card to read back
) -> list[str]:
    "Every forbidden phrase and every speedup claim without both a device and a runtime on its line; empty when the card is clean"
    found = [p for p in FORBIDDEN if re.search(rf"\b{re.escape(p)}\b", text, re.I)]
    for line in text.splitlines():
        claim, low = _SPEEDUP.search(line), line.lower()
        if claim and not (any(w in low for w in _DEVICES) and any(w in low for w in _RUNTIMES)):
            found.append(f"{claim.group().strip()} without both a device and a runtime on its line")
    return found
