# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_gate.ipynb.

# %% ../nbs/03_gate.ipynb #imports
from __future__ import annotations

import os
import subprocess
import sys
from dataclasses import asdict, dataclass
from pathlib import Path

from .card import check_card

# %% auto #0
__all__ = ['GateRow', 'run_gate', 'gate_passed']

# %% ../nbs/03_gate.ipynb #gate
@dataclass(slots=True)
class GateRow:
    "One publication condition and what it found"
    condition: int
    name: str
    passed: bool
    evidence: str

    def as_dict(self) -> dict: return asdict(self)


def _reload_hash(artifact_dir, python, pythonpath):
    "State hash of the artifact reloaded by a fresh interpreter with a scrubbed environment"
    code = ("from fastermodels import FasterModel, state_hash\n"
            f"print(state_hash(FasterModel.from_pretrained({str(artifact_dir)!r})))")
    run = subprocess.run([python, '-c', code], capture_output=True, text=True,
                         env={'PATH': os.environ.get('PATH', ''), 'PYTHONPATH': pythonpath or ''})
    if run.returncode != 0 or not run.stdout.strip():
        return None, (run.stderr.strip() or 'no output').splitlines()[-1]
    return run.stdout.strip().splitlines()[-1], ''


def _onnx_conditions(path, claimed):
    "Post-conditions read back from the exported ONNX itself when `onnx` is importable"
    if not path.exists(): return True, 'no model.onnx in the artifact directory'
    if not claimed: return False, 'model.onnx is there but the manifest has no files.onnx entry'
    opset, dynamic, n_q, n_dq, note = (claimed.get('opset'), claimed.get('dynamic_batch'),
                                       claimed.get('n_q'), claimed.get('n_dq'), '')
    try:
        import onnx
        graph = onnx.load(str(path))
        opset = max(i.version for i in graph.opset_import if i.domain in ('', 'ai.onnx'))
        dynamic = graph.graph.input[0].type.tensor_type.shape.dim[0].HasField('dim_param')
        n_q = sum(n.op_type == 'QuantizeLinear' for n in graph.graph.node)
        n_dq = sum(n.op_type == 'DequantizeLinear' for n in graph.graph.node)
    except ImportError:
        note = ' (onnx not importable, manifest values used)'
    qdq = (claimed.get('n_q') or 0) > 0 or (claimed.get('n_dq') or 0) > 0
    passed = opset == 17 and bool(dynamic) and (not qdq or ((n_q or 0) > 0 and (n_dq or 0) > 0))
    return passed, f"opset={opset} dynamic_batch={bool(dynamic)} n_q={n_q} n_dq={n_dq}{note}"


def run_gate(
    artifact_dir: str | Path,       # directory holding config.json, model.safetensors and README.md
    manifest: dict,                 # what the producer claims about the artifact
    *,
    python: str | None = None,      # interpreter of the fresh-interpreter reload (default: this one)
    pythonpath: str | None = None,  # the only PYTHONPATH that reload is given
) -> list[GateRow]:
    "Run the ten publication conditions on a local artifact directory"
    d, rows = Path(artifact_dir), []
    def add(condition, name, passed, evidence): rows.append(GateRow(condition, name, bool(passed), evidence))

    licence = manifest.get('license') or {}
    add(0, 'licence', licence.get('id') and licence.get('validated_by'),
        f"id={licence.get('id')!r} validated by {licence.get('validated_by')!r}")

    claimed = (manifest.get('hashes') or {}).get('safetensors')
    got, err = _reload_hash(d, python or sys.executable, pythonpath)
    add(1, 'fresh-interpreter reload', got is not None and got == claimed,
        f"reloaded {got} vs manifest {claimed}" if got else f"reload failed: {err}")

    parity = [p for p in (manifest.get('parity') or []) if p.get('kind') == 'same-precision']
    add(2, 'same-precision parity', parity and all((p.get('agreement') or 0) >= 0.995 for p in parity),
        '; '.join(f"{p.get('arms')} {p.get('agreement')}" for p in parity) or 'no same-precision parity arm')

    delta = manifest.get('delta') or {}
    lo, floor = delta.get('lo'), delta.get('floor')
    add(3, 'accuracy delta above floor', lo is not None and floor is not None and lo > floor,
        f"delta={delta.get('delta')} lo={lo} hi={delta.get('hi')} floor={floor}"
        + ('' if lo is not None else ' — no interval, so no verdict'))

    add(4, 'exported file', *_onnx_conditions(d / 'model.onnx', (manifest.get('files') or {}).get('onnx')))

    head, widths = manifest.get('head') or {}, manifest.get('widths') or {}
    add(5, 'head and widths', head.get('expected') is not None and head.get('num_classes') == head.get('expected') and widths,
        f"num_classes={head.get('num_classes')} expected={head.get('expected')} widths={len(widths)} layers")

    latency = manifest.get('latency_rows')
    add(6, 'latency', (isinstance(latency, list) and len(latency) > 0) or latency == 'non mesurée',
        f"{len(latency)} rows" if isinstance(latency, list) else f"latency_rows={latency!r}")

    card = d / 'README.md'
    flagged = check_card(card.read_text()) if card.exists() else None
    add(7, 'card', flagged == [], 'README.md missing' if flagged is None else (f"flagged: {flagged}" if flagged else 'nothing flagged'))

    clean = manifest.get('clean_reload') or {}
    add(8, 'clean-machine reload', clean.get('passed'), f"clean reload {clean}" if clean else 'not run')

    add(9, 'on-target claim', manifest.get('proof') or latency == 'non mesurée',
        'proof measured on the target' if manifest.get('proof') else
        ('no on-target claim, latency non mesurée' if latency == 'non mesurée' else 'latency rows without a proof on the target'))
    return rows


def gate_passed(
    rows: list[GateRow],  # what `run_gate` returned
) -> bool:
    "True when every condition passed"
    return all(r.passed for r in rows)
