# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_gate.ipynb.

# %% ../nbs/03_gate.ipynb #imports
from __future__ import annotations

import math
import os
import re
import subprocess
import sys
from dataclasses import asdict, dataclass
from pathlib import Path

from .card import _is_count, check_card
from .model import _FORMS

# %% auto #0
__all__ = ['BATCH_TOL', 'GateRow', 'run_gate', 'gate_passed']

# %% ../nbs/03_gate.ipynb #gate
BATCH_TOL = 1e-3   # float32 CPU convolutions differ by ~1e-5 between batch sizes; the failure this guards is of order 1


def _finite(v):
    "A number that was actually measured"
    return isinstance(v, (int, float)) and not isinstance(v, bool) and math.isfinite(v)


@dataclass(slots=True)
class GateRow:
    "One publication condition and what it found"
    condition: int
    name: str
    passed: bool
    evidence: str

    def as_dict(self) -> dict: return asdict(self)


def _hw(shape):
    "Height and width of one image, read off a shape like '3x160x160'"
    dims = [int(n) for n in re.findall(r'\d+', str(shape or ''))]
    return tuple(dims[-2:]) if len(dims) >= 2 else (224, 224)


def _reload(artifact_dir, python, pythonpath, input_shape):
    "Reload the artifact in a fresh interpreter with a scrubbed environment: the form it published, and its digest"
    h, w = _hw(input_shape)
    code = ("import hashlib, torch\n"
            "from pathlib import Path\n"
            "from fastermodels import load, state_hash\n"
            f"d = Path({str(artifact_dir)!r})\n"
            "m = load(d)\n"
            "if (d / 'model.safetensors').exists(): print('safetensors', state_hash(m))\n"
            "else:\n"
            f"    m(torch.zeros(1, 3, {h}, {w}))\n"
            "    print('torchscript', hashlib.sha256((d / 'model.torchscript.pt').read_bytes()).hexdigest())")
    run = subprocess.run([python, '-c', code], capture_output=True, text=True,
                         env={'PATH': os.environ.get('PATH', ''), 'PYTHONPATH': pythonpath or ''})
    if run.returncode != 0 or not run.stdout.strip():
        return None, None, (run.stderr.strip() or 'no output').splitlines()[-1]
    return (*run.stdout.strip().splitlines()[-1].split(), '')


def _onnx_conditions(path, claimed):
    "Post-conditions read back from the exported ONNX itself, never from what the manifest claims about it"
    if not claimed:
        return (False, 'model.onnx is there but the manifest has no files.onnx entry') if path.exists() \
            else (True, 'no model.onnx in the artifact directory')
    if not path.exists(): return False, 'model.onnx claimed in the manifest but missing'
    try:
        import onnx
    except ImportError:
        return False, 'install onnx to verify model.onnx'
    graph = onnx.load(str(path))
    opset = max(i.version for i in graph.opset_import if i.domain in ('', 'ai.onnx'))
    dynamic = graph.graph.input[0].type.tensor_type.shape.dim[0].HasField('dim_param')
    n_q = sum(n.op_type == 'QuantizeLinear' for n in graph.graph.node)
    n_dq = sum(n.op_type == 'DequantizeLinear' for n in graph.graph.node)
    qdq = (claimed.get('n_q') or 0) > 0 or (claimed.get('n_dq') or 0) > 0   # the manifest claims Q/DQ, n_q and n_dq come from the file
    passed = opset == 17 and dynamic and (not qdq or (n_q > 0 and n_dq > 0))
    return passed, f"opset={opset} dynamic_batch={dynamic} n_q={n_q} n_dq={n_dq}"


def run_gate(
    artifact_dir: str | Path,       # directory holding config.json, model.safetensors and README.md
    manifest: dict,                 # what the producer claims about the artifact
    *,
    python: str | None = None,      # interpreter of the fresh-interpreter reload (default: this one)
    pythonpath: str | None = None,  # the only PYTHONPATH that reload is given
) -> list[GateRow]:
    "Run the ten publication conditions on a local artifact directory"
    d, rows = Path(artifact_dir), []
    def add(condition, name, passed, evidence): rows.append(GateRow(condition, name, bool(passed), evidence))

    lic = manifest.get('license') or {}
    add(0, 'license', lic.get('id') and lic.get('validated_by'),
        f"id={lic.get('id')!r} validated by {lic.get('validated_by')!r}")

    if not any((d / _FORMS[f]).exists() for f in ('safetensors', 'torchscript')):
        add(1, 'fresh-interpreter reload', False,
            f"the artifact has neither {_FORMS['safetensors']} nor {_FORMS['torchscript']} to reload")
    else:
        form, got, err = _reload(d, python or sys.executable, pythonpath, manifest.get('input_shape'))
        claimed = (manifest.get('hashes') or {}).get(form)
        add(1, 'fresh-interpreter reload', got is not None and got == claimed,
            f"{form} reloaded {got} vs manifest {claimed}" if got else f"reload failed: {err}")

    parity = manifest.get('parity') or []
    same = [p for p in parity if p.get('kind') == 'same-precision']
    batch = [p for p in parity if p.get('kind') == 'batch-invariance']
    add(2, 'parity', same and all((p.get('agreement') or 0) >= 0.995 for p in same)
        and all(p.get('max_abs_diff') is not None and p['max_abs_diff'] <= BATCH_TOL for p in batch),
        '; '.join([f"{p.get('arms')} {p.get('agreement')}" for p in same]
                  + [f"{p.get('arms')} max_abs_diff={p.get('max_abs_diff')} (tolerance {BATCH_TOL})" for p in batch])
        or 'no same-precision parity arm')

    delta = manifest.get('delta') or {}
    target = delta.get('target', delta.get('floor'))   # `floor` is what this key was called; read for one release
    measured = all(_finite(delta.get(f)) for f in ('delta', 'lo', 'hi'))
    add(3, 'accuracy delta measured', measured,
        (f"arms={delta['arms']} " if 'arms' in delta else '')   # the producer names the row it judged
        + f"delta={delta.get('delta')} lo={delta.get('lo')} hi={delta.get('hi')}"
        + (f" target={target} {'met' if measured and delta['lo'] > target else 'not demonstrated'}" if target is not None else '')
        + ('' if measured else ' — no interval, so no verdict'))

    add(4, 'exported file', *_onnx_conditions(d / 'model.onnx', (manifest.get('files') or {}).get('onnx')))

    head, widths = manifest.get('head') or {}, manifest.get('widths') or {}
    add(5, 'head and widths', head.get('expected') is not None and head.get('num_classes') == head.get('expected') and widths,
        f"num_classes={head.get('num_classes')} expected={head.get('expected')} widths={len(widths)} layers")

    latency, measured = manifest.get('latency_rows'), manifest.get('rows') or []
    missing = [f"row {i} has no {f}" for i, r in enumerate(measured) for f in ('bytes', 'peak_activation_bytes', 'macs')
               if not (_is_count(r.get(f)) and r[f] >= 0)]
    add(6, 'size, memory, MACs and latency',
        measured and not missing and ((isinstance(latency, list) and len(latency) > 0) or latency == 'non mesurée'),
        '; '.join(missing) or (f"{len(measured)} rows measured, latency_rows="
                               + (f"{len(latency)} rows" if isinstance(latency, list) else f"{latency!r}")))

    card = d / 'README.md'
    flagged = check_card(card.read_text()) if card.exists() else None
    add(7, 'card', flagged == [], 'README.md missing' if flagged is None else (f"flagged: {flagged}" if flagged else 'nothing flagged'))

    clean = manifest.get('clean_reload') or {}
    add(8, 'clean-machine reload', clean.get('passed'), f"clean reload {clean}" if clean else 'not run')

    add(9, 'on-target claim', manifest.get('proof') or latency == 'non mesurée',
        'proof measured on the target' if manifest.get('proof') else
        ('no on-target claim, latency non mesurée' if latency == 'non mesurée' else 'latency rows without a proof on the target'))
    return rows


def gate_passed(
    rows: list[GateRow],  # what `run_gate` returned
) -> bool:
    "True when every condition passed"
    return all(r.passed for r in rows)
