# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_measurement.ipynb.

# %% ../nbs/04_measurement.ipynb #imports
from __future__ import annotations

import json
import math
import numbers
import re
from datetime import datetime
from pathlib import Path

# %% auto #0
__all__ = ['SCHEMA_VERSION', 'FIELDS', 'validate', 'status', 'key', 'throughput', 'read_rows', 'write_row', 'to_parquet']

# %% ../nbs/04_measurement.ipynb #schema
SCHEMA_VERSION = 1
_UTC = r'\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|\+00:00)'
_PCT = dict(ge=0, le=100)

# name -> type, required, and the declarative rules its value obeys; a field that is not required may be absent or None
FIELDS = {
    # identity and provenance
    'schema_version': dict(type=int, required=True, choices=(SCHEMA_VERSION,)),
    'run_id': dict(type=str, required=True),
    'measured_at': dict(type=str, required=True, pattern=_UTC, date=True),
    'series': dict(type=str, required=False),
    'harness_commit': dict(type=str, required=True),
    'fasterai_version': dict(type=str, required=False),
    'report_url': dict(type=str, required=False),
    'hf_repo': dict(type=str, required=False),
    # model
    'model_id': dict(type=str, required=True),
    'model_revision': dict(type=str, required=True),
    'task': dict(type=str, required=True, choices=('classification', 'detection')),
    'architecture': dict(type=str, required=True),
    'base_weights': dict(type=str, required=True),
    'weights_license': dict(type=str, required=True),
    'variant': dict(type=str, required=True),
    'recipe': dict(type=dict, required=True, json=True),
    'input_resolution': dict(type=int, required=True, gt=0),
    'macs': dict(type=int, required=True, gt=0),
    'params': dict(type=int, required=True, gt=0),
    'model_hash': dict(type=str, required=False),   # whatever fingerprint the exporter records, so not pinned
    'engine_hash': dict(type=str, required=True, pattern=r'[0-9a-f]{64}'),   # sha256 of the engine file that ran
    'size_mb': dict(type=float, required=True, gt=0),
    # device and runtime
    'device': dict(type=str, required=True),
    'device_host': dict(type=str, required=True, choices=('own', 'rented', 'partner')),
    'runtime': dict(type=str, required=True, choices=('tensorrt', 'openvino', 'onnxruntime', 'hailo', 'axelera')),
    'runtime_version': dict(type=str, required=True),
    'platform_version': dict(type=str, required=False),
    'precision': dict(type=str, required=True, choices=('fp32', 'fp16', 'int8', 'mixed')),
    'int8_mode': dict(type=str, required=False, choices=('implicit', 'explicit')),
    'power_mode': dict(type=str, required=False),
    'clocks_locked': dict(type=bool, required=False),
    'batch_size': dict(type=int, required=True, ge=1),
    # conditions
    'temp_start_c': dict(type=float, required=False),
    'temp_end_c': dict(type=float, required=False),
    'gpu_freq_mhz': dict(type=float, required=False, gt=0),
    'throttled': dict(type=bool, required=False),
    'warmup_s': dict(type=float, required=False, ge=0),
    'duration_s': dict(type=float, required=False, ge=0),
    'repeats': dict(type=int, required=True, ge=1),
    'latency_spread_pct': dict(type=float, required=False, ge=0),
    # latency
    'latency_ms_p50': dict(type=float, required=True, gt=0),
    'latency_ms_p90': dict(type=float, required=False, gt=0),
    'latency_ms_p99': dict(type=float, required=False, gt=0),
    'latency_scope': dict(type=str, required=True),
    'host_latency_ms': dict(type=float, required=False, gt=0),
    'latency_source': dict(type=str, required=True, choices=('measured', 'estimated')),
    # quality
    'metric': dict(type=str, required=True),
    'eval_set': dict(type=str, required=True),
    'eval_set_hash': dict(type=str, required=True),
    'dataset_license': dict(type=str, required=True),
    'eval_n': dict(type=int, required=True, gt=0),
    'accuracy': dict(type=float, required=True, **_PCT),
    'ci_low': dict(type=float, required=True, **_PCT),
    'ci_high': dict(type=float, required=True, **_PCT),
    'ci_method': dict(type=str, required=True, choices=('wilson', 'bootstrap')),
    'measured_through': dict(type=str, required=True, choices=('deployed_engine', 'dev_model')),
    'argmax_parity': dict(type=float, required=False, **_PCT),
    'parity_floor': dict(type=float, required=True, **_PCT),
    'baseline_run_id': dict(type=str, required=False),
}

def _item(o):
    "A numpy scalar as the Python number JSON knows"
    if isinstance(o, numbers.Number) and hasattr(o, 'item'): return o.item()
    raise TypeError(f'{type(o).__name__} is not JSON serializable')


def _json(obj, **kw): return json.dumps(obj, default=_item, allow_nan=False, **kw)
def _canonical(d): return _json(d, sort_keys=True, separators=(',', ':'))


def _is_json(v):
    try: return _json(v) is not None
    except (TypeError, ValueError): return False


def _is_date(v):
    try: return datetime.fromisoformat(v.replace('Z', '+00:00')) is not None   # Python 3.10 does not read 'Z'
    except ValueError: return False


_RULES = {
    'choices': (lambda v, c: v in c, 'not one of {}'),
    'gt': (lambda v, b: v > b, 'not > {}'),
    'ge': (lambda v, b: v >= b, 'not >= {}'),
    'le': (lambda v, b: v <= b, 'not <= {}'),
    'pattern': (lambda v, p: re.fullmatch(p, v) is not None, 'does not match {}'),
    'date': (lambda v, _: _is_date(v), 'is not a date'),
    'json': (lambda v, _: _is_json(v), 'is not JSON'),
}
_ORDERED = (('ci_low', 'accuracy', 'ci_high'), ('latency_ms_p50', 'latency_ms_p90', 'latency_ms_p99'))


def _typed(v, t):
    "`v` is a `t`; a bool is not a number, a numpy integer is an int, an int is a float, a float is finite"
    if isinstance(v, bool): return t is bool
    if t is int: return isinstance(v, numbers.Integral)
    if t is float: return isinstance(v, numbers.Real) and math.isfinite(v)
    return isinstance(v, t)


def _field_problems(name, v):
    "The problems of one field value, against its spec"
    spec = FIELDS[name]
    if v is None: return [f'{name}: missing'] if spec['required'] else []
    if not _typed(v, spec['type']): return [f'{name}: expected {spec["type"].__name__}, got {v!r}']
    return [f'{name}: {v!r} {msg.format(spec[r])}' for r, (ok, msg) in _RULES.items() if r in spec and not ok(v, spec[r])]


def _cross_problems(row):
    "Problems between fields; each field involved is already well typed"
    p, mode = row['precision'], row.get('int8_mode')
    out = []
    if p == 'int8' and mode is None: out.append('int8_mode: missing, required when precision is int8')
    if p != 'int8' and mode is not None: out.append(f'int8_mode: {mode!r} given for precision {p!r}')
    for fields in _ORDERED:
        vals = [(f, row[f]) for f in fields if row.get(f) is not None]
        if [v for _, v in vals] != sorted(v for _, v in vals):
            out.append(f"{', '.join(fields)}: not in order, " + ', '.join(f'{f}={v}' for f, v in vals))
    return out


def validate(
    row: dict,  # one measurement row
) -> list[str]:
    "Every structural problem of `row`, each prefixed by its field name; an empty list means well formed"
    if not isinstance(row, dict): return [f'row: expected a dict, got {type(row).__name__}']
    out = [f'{k}: unknown field' for k in row if k not in FIELDS]
    for name in FIELDS: out += _field_problems(name, row.get(name))
    return out or _cross_problems(row)

# %% ../nbs/04_measurement.ipynb #status
# field, when its value makes the measurement invalid, and why; a field that is None is not recorded
_VALIDITY = (
    ('measured_through', lambda v, r, m: v != 'deployed_engine', 'accuracy not measured through the deployed engine'),
    ('latency_source', lambda v, r, m: v != 'measured', 'latency not measured on the device'),
    ('argmax_parity', lambda v, r, m: v < r['parity_floor'], '{v} below parity_floor {r[parity_floor]}'),
    ('throttled', lambda v, r, m: v, 'the device throttled during the session'),
    ('latency_spread_pct', lambda v, r, m: v > m, '{v} above {m}'),
)


def status(
    row: dict,                    # one measurement row
    max_spread_pct: float = 5.0,  # largest (max-min)/median latency spread over repeats, in percent
) -> tuple[str, list[str]]:
    "('VALID', []) if `row` is a usable measurement, else ('INVALID', reasons); not a verdict against any budget"
    reasons = validate(row)
    if reasons: return 'INVALID', reasons
    for f, bad, why in _VALIDITY:
        v = row.get(f)
        if v is None: reasons.append(f'{f}: not recorded')
        elif bad(v, row, max_spread_pct): reasons.append(f'{f}: ' + why.format(v=v, r=row, m=max_spread_pct))
    return ('INVALID', reasons) if reasons else ('VALID', [])

# %% ../nbs/04_measurement.ipynb #key
def key(
    row: dict,  # one measurement row
) -> tuple:
    "The identity a row is unique on; a software update on the device gives a new key"
    return (row['model_id'], row['model_revision'], row['variant'], _canonical(row['recipe']),
            row['input_resolution'], row['device'], row['runtime'], row['runtime_version'],
            row.get('platform_version'), row['precision'], row.get('int8_mode'), row['batch_size'],
            row['measured_at'])


def throughput(
    row: dict,  # one measurement row
) -> float:
    "Images per second at the timed batch, derived from the median latency and never stored"
    return row['batch_size'] * 1000 / row['latency_ms_p50']

# %% ../nbs/04_measurement.ipynb #io
def _parse(text, path):
    "The rows of a JSON Lines text; a malformed line raises with its number"
    rows = []
    for i, line in enumerate(text.splitlines(), 1):
        if not line.strip(): continue
        try: r = json.loads(line)
        except json.JSONDecodeError as e: raise ValueError(f'{path}:{i}: not JSON ({e.msg})') from None
        if not isinstance(r, dict): raise ValueError(f'{path}:{i}: not a JSON object')
        rows.append(r)
    return rows


def read_rows(
    path: str | Path,  # a JSON Lines file of measurement rows
) -> list[dict]:
    "The rows of `path`, as stored; `status` judges them"
    return _parse(Path(path).read_text(), path)


def write_row(
    path: str | Path,  # a JSON Lines file, created if absent
    row: dict,         # the measurement row to append
):
    "Append `row` to `path`; refuses a malformed row and a row whose key is already in the file"
    problems = validate(row)
    if problems: raise ValueError('row refused: ' + '; '.join(problems))
    p, k = Path(path), key(row)
    text = p.read_text() if p.exists() else ''
    if k in {key(r) for r in _parse(text, path)}: raise ValueError(f'row refused: key {k} already in {path}')
    # ponytail: no file lock, one writer at a time
    with p.open('a') as f: f.write(('\n' if text and not text.endswith('\n') else '') + _json(row) + '\n')

# %% ../nbs/04_measurement.ipynb #parquet
def to_parquet(
    rows: list[dict],  # well-formed measurement rows, e.g. from `read_rows`
    path: str | Path,  # the Parquet file to write
):
    "Write `rows` as one Parquet table, one column per field in `FIELDS` order, dict fields as canonical JSON"
    try:
        import pandas as pd
        import pyarrow  # noqa: F401
    except ImportError: raise ImportError("to_parquet needs pandas and pyarrow: pip install 'fastermodels[parquet]'") from None
    for i, r in enumerate(rows):
        problems = validate(r)
        if problems: raise ValueError(f'row {i} refused: ' + '; '.join(problems))
    table = [{k: _canonical(r[k]) if FIELDS[k]['type'] is dict else r.get(k) for k in FIELDS} for r in rows]
    pd.DataFrame(table, columns=list(FIELDS)).to_parquet(path, engine='pyarrow', index=False)
