# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_model.ipynb.

# %% ../nbs/00_model.ipynb #imports
from __future__ import annotations

import hashlib
import importlib
from collections.abc import Callable

import torch.nn as nn
from huggingface_hub import PyTorchModelHubMixin

# %% auto #0
__all__ = ['LAYER_TYPES', 'resolve', 'spec_from', 'state_hash', 'FasterModel']

# %% ../nbs/00_model.ipynb #layer-types
LAYER_TYPES = {'Conv2d': nn.Conv2d, 'Linear': nn.Linear, 'BatchNorm2d': nn.BatchNorm2d, 'BatchNorm1d': nn.BatchNorm1d}

_BN_ARGS = ('num_features', 'eps', 'momentum', 'affine', 'track_running_stats')
_ARGS = {'Conv2d': ('in_channels', 'out_channels', 'kernel_size', 'stride', 'padding', 'dilation', 'groups', 'padding_mode'),
         'Linear': ('in_features', 'out_features'),
         'BatchNorm2d': _BN_ARGS,
         'BatchNorm1d': _BN_ARGS}

# %% ../nbs/00_model.ipynb #resolve
def resolve(
    source: str,  # dotted path of a model factory, e.g. 'torchvision.models.resnet18'
) -> Callable:
    "Import the model factory `source` points to"
    module, _, attr = source.rpartition('.')
    try:
        return getattr(importlib.import_module(module), attr)
    except (ImportError, AttributeError, ValueError) as e:
        raise ImportError(f"cannot resolve source '{source}' — pass a dotted path to a model factory, "
                          f"e.g. 'torchvision.models.resnet18' ({e})") from e

# %% ../nbs/00_model.ipynb #spec-from
def _plain(v):
    "JSON-native value (torch keeps sizes as tuples)"
    return list(v) if isinstance(v, tuple) else v


def spec_from(
    model: nn.Module,  # model whose optimized layers are recorded
) -> dict:
    "Rebuild spec: the constructor arguments of every Conv2d, Linear and BatchNorm leaf, read off the live model"
    spec = {}
    for name, m in model.named_modules():
        kind = type(m).__name__
        if LAYER_TYPES.get(kind) is not type(m): continue   # exact type: a subclass would not rebuild from these arguments
        spec[name] = {'type': kind, **{a: _plain(getattr(m, a)) for a in _ARGS[kind]}}
        if kind in ('Conv2d', 'Linear'): spec[name]['bias'] = m.bias is not None
    return spec

# %% ../nbs/00_model.ipynb #state-hash
def state_hash(
    obj: nn.Module | dict,  # a model or a state dict
) -> str:
    "sha256 over every state dict entry: key, shape, dtype and raw bytes"
    sd = obj.state_dict() if isinstance(obj, nn.Module) else obj
    h = hashlib.sha256()
    for k in sorted(sd):
        t = sd[k]
        h.update(f"{k}{tuple(t.shape)}{t.dtype}".encode())
        h.update(t.detach().cpu().contiguous().numpy().tobytes())
    return h.hexdigest()

# %% ../nbs/00_model.ipynb #faster-model
def _swap(net, name, kw):
    "Replace the leaf at `name` by a module rebuilt from its spec"
    parent, _, child = name.rpartition('.')
    try:
        host = net.get_submodule(parent)
        getattr(host, child)
    except AttributeError as e:
        raise KeyError(f"module '{name}' is not in the source model — check `modules` against the source factory") from e
    kw = dict(kw)
    setattr(host, child, LAYER_TYPES[kw.pop('type')](**kw))


class FasterModel(nn.Module, PyTorchModelHubMixin,
                  library_name='fastermodels',
                  repo_url='https://github.com/FasterAI-Labs/fastermodels',
                  tags=['fasterai']):
    "A model optimized by fasterai: a source factory, the rebuild spec of its layers, and its weights"

    def __init__(self,
                 source: str,                        # dotted path of the model factory
                 source_kwargs: dict | None = None,  # arguments the factory is called with
                 modules: dict | None = None,        # rebuild spec, as returned by `spec_from`
                 recipe: dict | None = None,         # the steps that produced the weights
                 provenance: dict | None = None,     # versions, commits, weights the source started from
    ):
        super().__init__()
        self.net = resolve(source)(**(source_kwargs or {}))
        for name, kw in (modules or {}).items(): _swap(self.net, name, kw)
        self.recipe, self.provenance = recipe, provenance   # these arguments are what the mixin writes to config.json

    def forward(self, x): return self.net(x)

    @classmethod
    def wrap(cls,
             model: nn.Module,                   # the optimized model to publish
             source: str,                        # dotted path of the model factory it came from
             source_kwargs: dict | None = None,  # arguments the factory is called with
             recipe: dict | None = None,         # the steps that produced the weights
             provenance: dict | None = None,     # versions, commits, weights the source started from
    ) -> "FasterModel":
        "Wrap an optimized model, reading its rebuild spec off its layers; returned in eval mode"
        fm = cls(source=source, source_kwargs=source_kwargs, modules=spec_from(model), recipe=recipe, provenance=provenance)
        fm.net.load_state_dict(model.state_dict(), strict=True)
        return fm.eval()

    @classmethod
    def _from_pretrained(cls, **kwargs):
        "Load strict, so a spec that disagrees with the weights raises instead of loading in part, and in eval mode"
        return super()._from_pretrained(**{**kwargs, 'strict': True}).eval()
