project:
  type: website
  render:
    - "*"
    - "!tests/**"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  open-graph: true
  repo-actions: [issue]
  page-footer: "&copy; By Nathan Hubens"
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: "https://github.com/FasterAI-Labs/fastermodels"
  sidebar:
    style: floating
    collapse-level: 1
    contents:
      - index.ipynb
      - section: Tutorials
        contents:
        - tutorials/load_and_check.ipynb
      - section: API
        contents:
        - 00_model.ipynb
        - 01_eval.ipynb
        - 02_card.ipynb
        - 03_gate.ipynb

metadata-files: [nbdev.yml]
